%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.2

-ifndef(protos).
-define(protos, true).

-define(protos_gpb_version, "4.0.2").

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record('Person',
        {name                   :: iolist(),        % = 1
         id                     :: integer(),       % = 2, 32 bits
         email                  :: iolist() | undefined % = 3
        }).
-endif.

-endif.
